name: Pre-commit
description: Run pre-commit checks

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
      shell: bash
    - name: Cache pre-commit hooks
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always --all-files
      shell: bash
